'use client';
import {useEffect,useState} from 'react';
import {Star,Plus,Spade,LayoutDashboard,Trophy,CalendarDays,MapPin,ChevronRight,X,Check,NotebookPen,TrendingUp,Wallet,Target,BarChart3,Trash2} from 'lucide-react';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Tournament,cost,profit,beforeSplitProfit,shopShare,takeHome,validateRecord} from '@/lib/tournament';
const money=(n:number)=>new Intl.NumberFormat('ko-KR').format(n);
const won=(n:number)=>(n<0?'-':'')+'₩'+money(Math.abs(n));
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const fresh=()=>({id:'',date:today(),name:'',venue:'',buyin:50000,entries:1,extra:0,prize:0,rank:null,players:null,itm:0,notes:''} as Tournament);
export default function PokerApp({initialView='overview'}:{initialView?:string}){
 const [records,setRecords]=useState<Tournament[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[form,setForm]=useState<Tournament>(fresh),[busy,setBusy]=useState(false),[formError,setFormError]=useState(''),[deleting,setDeleting]=useState(false),[view,setView]=useState(initialView),[period,setPeriod]=useState('all'),[saved,setSaved]=useState(''),[editReady,setEditReady]=useState(initialView!=='entry');
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/tournaments');const d:any=await r.json();if(!r.ok)throw Error(d.error);setRecords(d.records);if(initialView==='entry'){const id=new URLSearchParams(window.location.search).get('id');if(id){const record=d.records.find((x:Tournament)=>x.id===id);if(!record)throw Error('기록을 찾을 수 없습니다.');setForm(record);}setEditReady(true);}}catch(e){setError(e instanceof Error?e.message:'기록을 불러오지 못했습니다.');}finally{setLoading(false);}}
 useEffect(()=>{load();if(initialView==='overview'&&new URLSearchParams(window.location.search).get('view')==='records')setView('records');if(initialView==='overview'&&new URLSearchParams(window.location.search).get('saved')==='1')setSaved('기록을 저장했습니다.');},[]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'start_tournament_record',title:'대회 기록 입력',description:'대회 기록 입력 페이지로 이동합니다. 저장은 사용자가 입력 후 완료합니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:any)=>{if(!input||Object.keys(input).length)throw Error('입력값이 필요하지 않습니다.');window.location.assign('/record');return {navigating:true};}},{signal:lifecycle.signal})).catch(console.error);}catch(e){console.error(e);}return ()=>lifecycle.abort();},[]);
 const list=records.filter(r=>period==='all'||r.date.startsWith(today().slice(0,period==='year'?4:7)));
 const investment=list.reduce((s,r)=>s+cost(r),0),prizes=list.reduce((s,r)=>s+r.prize,0),shops=list.reduce((s,r)=>s+shopShare(r),0),received=list.reduce((s,r)=>s+takeHome(r),0),privateNet=received-investment,net=prizes-investment,roi=investment?net/investment*100:0,itm=list.length?list.filter(r=>r.itm).length/list.length*100:0;
 const entryCount=list.reduce((s,r)=>s+r.entries,0),wins=list.filter(r=>r.rank===1).length;
 const sorted=[...list].sort((a,b)=>a.date.localeCompare(b.date));let acc=0;const points=[0,...sorted.map(r=>acc+=beforeSplitProfit(r))];const low=Math.min(0,...points),high=Math.max(0,...points),range=high-low||1;const point=(v:number,i:number)=>`${50+i/Math.max(1,points.length-1)*860},${185-(v-low)/range*140}`;const path=points.map((v,i)=>(i?'L':'M')+point(v,i)).join(' ');const zero=185-(0-low)/range*140;
 function start(r?:Tournament){window.location.assign(r?'/record?id='+encodeURIComponent(r.id):'/record');}
 function field(k:keyof Tournament,v:any){setForm(f=>({...f,[k]:v}));}
 async function save(e:React.FormEvent){e.preventDefault();setFormError('');try{validateRecord(form);}catch(e){setFormError(e instanceof Error?e.message:'입력값을 확인해 주세요.');return;}setBusy(true);try{const r=await fetch('/api/tournaments',{method:form.id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d:any=await r.json();if(!r.ok)throw Error(d.error);setRecords(prev=>[...prev.filter(x=>x.id!==d.record.id),d.record].sort((a,b)=>b.date.localeCompare(a.date)));window.location.assign('/?saved=1');}catch(e){setFormError(e instanceof Error?e.message:'저장하지 못했습니다.');}finally{setBusy(false);}}
 async function remove(){setBusy(true);try{const r=await fetch('/api/tournaments',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:form.id})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setRecords(p=>p.filter(x=>x.id!==form.id));setDeleting(false);window.location.assign('/');}catch(e){setDeleting(false);setFormError(e instanceof Error?e.message:'삭제하지 못했습니다.');}finally{setBusy(false);}}
 const recordForm=(<form onSubmit={save}><div className="form-grid"><label>날짜<input required type="date" value={form.date} onChange={e=>field('date',e.target.value)}/></label><label>실제 총 바이인 금액 (원)<input required type="number" inputMode="numeric" min="0" max="10000000000" step="1" value={Number.isNaN(form.buyin)?'':form.buyin} onChange={e=>field('buyin',e.target.value===''?NaN:Number(e.target.value))}/><small>얼리 할인 반영 · 실제 지출한 총액</small></label><label>바이인 횟수<input required type="number" inputMode="numeric" min="1" max="1000" step="1" value={Number.isNaN(form.entries)?'':form.entries} onChange={e=>field('entries',e.target.value===''?NaN:Number(e.target.value))}/><small>최초 참가 포함 · 재진입 1회면 총 2회</small></label><label>머니인 금액 (원)<input required type="number" inputMode="numeric" min="0" max="10000000000" step="1" value={Number.isNaN(form.prize)?'':form.prize} onChange={e=>setForm(f=>({...f,prize:e.target.value===''?NaN:Number(e.target.value),itm:Number(e.target.value)>0?1:0}))}/></label><label>최종 순위<input type="number" inputMode="numeric" min="1" max="10000000" step="1" placeholder="선택 입력" value={form.rank??''} onChange={e=>field('rank',e.target.value?Number(e.target.value):null)}/></label><label className="checkbox-label full"><Checkbox checked={!!form.itm} onCheckedChange={v=>field('itm',v===true?1:0)}/>머니인 (ITM)<small>바운티만 받은 경우 등은 직접 구분하세요.</small></label><label className="full">메모<textarea maxLength={2000} rows={2} placeholder="기억할 핸드나 플레이를 남겨보세요." value={form.notes} onChange={e=>field('notes',e.target.value)}/></label></div><div className="form-result settlement-grid public-amounts"><span>총 바이인 금액<strong>{won(cost(form)||0)}</strong></span><span>머니인 금액<strong>{won(form.prize||0)}</strong></span><span>순수익<strong className={beforeSplitProfit(form)<0?'negative':'positive'}>{won(beforeSplitProfit(form)||0)}</strong></span></div>{formError&&<p className="form-error" role="alert">{formError}</p>}<div className="form-actions">{form.id&&<button type="button" className="delete-button" disabled={busy} onClick={()=>setDeleting(true)}><Trash2 size={17}/>삭제</button>}<a className="secondary-button" href="/">취소</a><button type="submit" className="primary-button" disabled={busy||!editReady}>{busy?'저장 중…':!editReady?'기록 불러오는 중…':<><Check size={18}/>기록 저장</>}</button></div></form>);
 return <div className="app-shell"><aside className="sidebar"><a className="brand" href="/"><span className="brand-icon"><Spade size={23} fill="currentColor"/></span><span>POKER<span className="brand-light">LEDGER</span></span></a><div className="nav-label">MY POKER</div><button className={'nav-item '+(view==='overview'?'active':'')} onClick={()=>{if(initialView!=='overview')window.location.assign('/');else setView('overview');}}><LayoutDashboard size={19}/>대시보드</button><button className={'nav-item '+(view==='records'?'active':'')} onClick={()=>{if(initialView!=='overview')window.location.assign('/?view=records');else setView('records');}}><NotebookPen size={19}/>토너먼트 기록<span className="nav-count">{records.length}</span></button><div className="sidebar-bottom"><div className="player-avatar">PL</div><div><strong>나의 포커 기록</strong><small>TOURNAMENT TRACKER</small></div></div></aside>
 <main><header className="topbar"><span>MY POKER / <b>{view==='settlement'?'SUMMARY':view==='entry'?'NEW RECORD':view==='overview'?'OVERVIEW':'TOURNAMENTS'}</b></span><span className="private-label">개인 기록</span></header><div className="main-content"><div className="page-heading"><div><p className="eyebrow">TOURNAMENT ANALYTICS</p><h1>{view==='settlement'?'정산':view==='entry'?(form.id?'기록 수정':'대회 기록 입력'):view==='overview'?'대시보드':'토너먼트 기록'}<span className="heading-dot">.</span></h1><p className="subtitle">한 번의 플레이부터, 나만의 기록으로.</p></div>{view!=='entry'&&<button className="primary-button" onClick={()=>start()}><Plus size={19}/>대회 기록</button>}</div>
 {saved&&<p className="save-success" role="status"><Check size={16}/>{saved}</p>}
 {view==='entry'&&<section className="entry-card"><div className="section-heading"><h2>{form.id?'대회 기록 수정':'참가 정보와 결과'}</h2><CalendarDays size={21}/></div>{recordForm}</section>}
 {error&&view==='entry'&&<div className="error-banner" role="alert">{error}<button onClick={load}>다시 시도</button></div>}
 {view!=='entry'&&<>
 <div className="period-row"><div className="segmented" aria-label="기록 기간">{[['all','전체 기간'],['year','올해'],['month','이번 달']].map(([v,l])=><button key={v} className={period===v?'selected':''} onClick={()=>setPeriod(v)}>{l}</button>)}</div><span className="period-caption">KRW · 원화 기준</span></div>
 {error&&<div className="error-banner" role="alert">{error}<button onClick={load}>다시 시도</button></div>}
 {view==='settlement'?<> <section className="totals-card private-totals"><div className="section-heading"><h2>누적 정산</h2><span className="period-caption">선택 기간 · {list.length}대회</span></div><div className="settlement-grid cumulative"><div><span>총 바이인 횟수</span><strong>{loading?'—':money(entryCount)+'회'}</strong></div><div><span>총 바이인 금액</span><strong>{loading?'—':won(investment)}</strong></div><div><span>총 머니인</span><strong>{loading?'—':won(prizes)}</strong></div><div><span>총 가게 몫 · 60%</span><strong>{loading?'—':won(shops)}</strong></div><div><span>총 내 수령액</span><strong>{loading?'—':won(received)}</strong><small>바이인 회수분 포함</small></div><div><span>총 내 순수익</span><strong className={privateNet<0?'negative':'positive'}>{loading?'—':won(privateNet)}</strong></div></div></section>
<a className="secondary-button" href="/">대시보드로 돌아가기</a></>:<> <section className="totals-card"><div className="section-heading"><h2>누적 기록</h2><span className="period-caption">선택 기간 · {list.length}대회 · 바이인 {entryCount}회</span></div><div className="settlement-grid cumulative public-amounts"><div><span>총 바이인 금액</span><strong>{loading?'—':won(investment)}</strong></div><div><span>총 머니인 금액</span><strong>{loading?'—':won(prizes)}</strong></div><div><span>순수익</span><strong className={net<0?'negative':'positive'}>{loading?'—':won(net)}</strong></div></div></section>
 {view==='overview'&&<><section className="stats-grid"><div className="stat-card featured"><div className="stat-label">순수익<TrendingUp size={19}/></div><strong className={net<0?'negative':''}>{loading?'—':won(net)}</strong><span className="stat-foot">머니인 − 총 바이인 금액</span></div><div className="stat-card"><div className="stat-label">ROI<BarChart3 size={19}/></div><strong className={roi<0?'negative':'positive'}>{loading?'—':roi.toFixed(1)+'%'}<small>수익률</small></strong><span className="stat-foot">순수익 ÷ 총 투입금</span></div><div className="stat-card"><div className="stat-label">ITM<Target size={19}/></div><strong>{loading?'—':itm.toFixed(1)+'%'}<small>머니인 비율</small></strong><span className="stat-foot">{list.filter(r=>r.itm).length} / {list.length} 대회 머니인</span></div><div className="stat-card"><div className="stat-label">참가 대회<Trophy size={19}/></div><strong>{loading?'—':list.length}<small>회</small></strong><span className="stat-foot">총 바이인 {entryCount}회 · 우승 {wins}회</span></div></section>
 <section className="chart-card"><div className="section-heading"><div><h2>누적 수익</h2><p>기록이 쌓일수록 선명해지는 나의 플레이</p></div><span className="chart-legend"><i/>순수익</span></div><div className="chart-wrap"><svg viewBox="0 0 940 235" role="img" aria-label="누적 순수익 그래프"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#42dca3" stopOpacity=".18"/><stop offset="100%" stopColor="#42dca3" stopOpacity="0"/></linearGradient></defs>{[45,92,138,185].map((y,i)=><g key={y}><line x1="50" x2="910" y1={y} y2={y} stroke="#27332f" strokeDasharray="3 5"/><text x="42" y={y+4} textAnchor="end" fill="#7d9187" fontSize="11">{money(Math.round(high-i/3*(high-low)))}</text></g>)}<line x1="50" x2="910" y1={zero} y2={zero} stroke="#547266" strokeOpacity=".5"/>{list.length>0&&<><path d={path+' L910,185 L50,185 Z'} fill="url(#area)"/><path d={path} fill="none" stroke="#42dca3" strokeWidth="3" strokeLinejoin="round"/><circle cx="910" cy={185-(points[points.length-1]-low)/range*140} r="4" fill="#42dca3"/></>}<text x="50" y="218" fill="#82938a" fontSize="12">{sorted[0]?.date||'시작'}</text><text x="910" y="218" textAnchor="end" fill="#82938a" fontSize="12">{sorted.at(-1)?.date||'현재'}</text></svg>{!list.length&&<div className="chart-empty"><TrendingUp size={25}/><strong>첫 기록부터 수익 그래프가 시작됩니다</strong><span>대회 결과를 입력해 나의 흐름을 확인하세요.</span></div>}</div></section></>}
 <section className="records-card"><div className="section-heading"><div><h2>{view==='overview'?'최근 토너먼트':'모든 토너먼트'}<span className="count-tag">{list.length}</span></h2></div>{view==='overview'&&list.length>5&&<button className="text-button" onClick={()=>{if(initialView!=='overview')window.location.assign('/?view=records');else setView('records');}}>전체 보기<ChevronRight size={16}/></button>}</div>{loading?<div className="empty-records">기록을 불러오는 중입니다…</div>:!list.length?<div className="empty-records"><span className="empty-icon"><NotebookPen size={26}/></span><h3>아직 기록된 대회가 없어요</h3><p>날짜와 바이인 횟수, 최종 결과를 남겨보세요.</p><button className="secondary-button" onClick={()=>start()}><Plus size={17}/>첫 대회 기록하기</button></div>:<div className="record-list">{(view==='overview'?list.slice(0,5):list).map(r=><button className="record-row" key={r.id} onClick={()=>start(r)}><div className="record-title"><span className={'record-emblem '+(r.rank===1?'gold':'')}>{r.rank===1?<Trophy size={19}/>:<Spade size={18}/>}</span><div><strong>{r.date.replaceAll('-','.')} 토너먼트{!!r.itm&&<span className="itm-tag">ITM</span>}</strong><small>바이인 {r.entries}회</small></div></div><span className="record-rank">{r.rank?money(r.rank)+'위':'순위 미입력'}<ChevronRight size={15}/></span><div className="settlement-grid record-settlement public-amounts"><span>바이인 금액<strong>{won(cost(r))}</strong><small>총 {r.entries}회</small></span><span>머니인<strong>{won(r.prize)}</strong></span><span>순수익<strong className={beforeSplitProfit(r)<0?'negative':'positive'}>{beforeSplitProfit(r)>0?'+':''}{won(beforeSplitProfit(r))}</strong></span></div></button>)}</div>}</section></>}</>}<footer className="page-footer"><Spade size={13}/> POKER LEDGER <span>당신의 플레이를 기록하세요.</span><a className="star-link" href="/summary" aria-label="정산 페이지"><Star size={16}/></a></footer></div></main>
 <nav className="mobile-nav"><button className={view==='overview'?'active':''} onClick={()=>{if(initialView!=='overview')window.location.assign('/');else setView('overview');}}><LayoutDashboard size={20}/>대시보드</button><button onClick={()=>start()}><Plus size={23}/>대회 기록</button><button className={view==='records'?'active':''} onClick={()=>{if(initialView!=='overview')window.location.assign('/?view=records');else setView('records');}}><NotebookPen size={20}/>기록 목록</button></nav>
 <AlertDialog open={deleting} onOpenChange={setDeleting}><AlertDialogContent className="delete-dialog"><AlertDialogTitle>이 대회 기록을 삭제할까요?</AlertDialogTitle><AlertDialogDescription>삭제한 기록은 복구할 수 없습니다.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel disabled={busy}>취소</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();remove();}}>삭제</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>;
}
